wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.7.16
    cli_version: 0.14.2
    framework: huggingface
    huggingface_version: 4.27.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1681195796.511862
    t:
      1:
      - 1
      - 11
      - 30
      - 49
      - 51
      - 55
      - 71
      - 85
      3:
      - 13
      - 15
      - 23
      4: 3.7.16
      5: 0.14.2
      6: 4.27.1
      8:
      - 5
